mysite/api/urls.py
from django.urls import include
from django.urls import path
from . import views
from django.conf import settings

# app_name = "api"
# TODO: use namespace above
# TODO: check if tobar notification stuff did not break
# TODO: check if the friends page did not break 

urlpatterns = [


    path("ping/", views.Ping.as_view(), name="Ping"),

    path("usernames/<starts_with>/", views.UsernameList.as_view(), name="usernamelist"),
    path("usernames/", views.UsernameList.as_view(), name="usernamelist"),

    path("notification/<int:id>/clear/", views.ClearNotification.as_view(), name="clear_notification"),
    path("notifications/clear/", views.ClearAllNotification.as_view(), name="clear_all_notifications"),
]

mysite/calorietracker/urls.py
import debug_toolbar
from allauth.account.views import LoginView as AllAuthLoginView
from django.conf import settings
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    path("", views.LandingPage.as_view(), name="welcome"),
    path("home/", views.LandingPage.as_view(), name="home"),
    path("profile/", views.Profile.as_view(), name="profile"),
    path("profile/<slug:slug>", views.Profile.as_view(), name="profile"),
    path("logdata/", views.LogData.as_view(), name="logdata"),
    path("logs/", views.ViewLogs.as_view(), name="logs"),
    path("logdata/<pk>/update/", views.UpdateLogData.as_view(), name="UpdateLogData"),
    path("logdata/<pk>/delete/", views.DeleteLogData.as_view(), name="DeleteLogData"),
    path("analytics/<uuid>/", views.Analytics.as_view(), name="analytics"),
    path("analytics/", views.Analytics.as_view(), name="analytics"),
    # AUTH
    path("register/", views.Register.as_view(), name="register"),
    path("login/", AllAuthLoginView.as_view(), name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
    path("change-password/", views.PasswordChange.as_view(), name="change-password"),
    path("settings/", views.Settings.as_view(), name="settings"),
    path("feedback/", views.Feedback.as_view(), name="feedback"),
    # IMPORT
    path("import/csv", views.ImportCSV.as_view(), name="importcsv"),
    path("import/mfp", views.ImportMFP.as_view(), name="importmfp"),
    path(
        "import/credentials/mfp/",
        views.ImportMFPCredentials.as_view(),
        name="import-credentials-mfp",
    ),
    path(
        "import/credentials/mfp/create/",
        views.ImportMFPCredentialsCreate.as_view(),
        name="import-credentials-mfp-create",
    ),
    path(
        "import/credentials/mfp/update/",
        views.ImportMFPCredentialsUpdate.as_view(),
        name="import-credentials-mfp-update",
    ),
    # CONTACTS / FRIENDSHIP / COACH-CLIENT
    path("contacts/", views.Contacts.as_view(), name="contacts"),
    path("clients/", views.Clients.as_view(), name="clients"),
    path("accept-friend/", views.AcceptFriend.as_view(), name="acceptfriend"),
    path("reject-friend/", views.RejectFriend.as_view(), name="rejectfriend"),
    path("remove-friend/", views.RemoveFriend.as_view(), name="removefriend"),
    path(
        "send-friend-request/",
        views.SendFriendRequest.as_view(),
        name="sendfriendrequest",
    ),
    path(
        "cancel-friend-request/",
        views.CancelFriendRequest.as_view(),
        name="cancelfriendrequest",
    ),
    path(
        "add-coach/",
        views.AddCoach.as_view(),
        name="addcoach",
    ),
    path(
        "add-client/",
        views.AddClient.as_view(),
        name="addclient",
    ),
    path(
        "remove-coach-client/",
        views.RemoveCoachClient.as_view(),
        name="removecoachclient",
    ),
    # MISC
    path("referral-program/", views.Referral.as_view(), name="referral-program"),
    path("privacy-policy/", views.PrivacyPolicy.as_view(), name="privacy-policy"),
    path("subscription/", views.Subscription.as_view(), name="subscription"),
    path("terms-and-conditions/", views.Terms.as_view(), name="terms-and-conditions"),
]

if settings.DEBUG:

    # Test Sentry error reporting
    def trigger_error(request):
        division_by_zero = 1 / 0

    urlpatterns.append(path("sentry-debug/", trigger_error))

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from decorator_include import decorator_include
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage


from multifactor.decorators import multifactor_protected
import debug_toolbar

urlpatterns = [
    path(
        "",
        decorator_include(
            multifactor_protected(factors=0), include("calorietracker.urls")
        ),
    ),
    path("multifactor/", include("multifactor.urls")),
    path("api/", include("api.urls")),
    # re_path(
    #     r"^referrals/", include("pinax.referrals.urls",
    #                             namespace="pinax_referrals")
    # ),
    # re_path(r"^announcements/", include("pinax.announcements.urls",
    #                                     namespace="pinax_announcements")),
    # re_path(r"^messages/", include("pinax.messages.urls",
    #                                namespace="pinax_messages")),
    # re_path(r"^payments/", include("djstripe.urls", namespace="djstripe")), deprecated
    path("accounts/", include("allauth.urls")),
    path("friendship/", include("friendship.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    # Favicon redirect for legacy devices
    # This needs to be outside of any multifactor protected views and therefore cant be in the calorietracker app urls
    path(
        "favicon.ico/",
        RedirectView.as_view(
            url=staticfiles_storage.url("favicon/favicon.ico")),
    ),
    # Apple-touch-icon redirect for ios safari and add to homescreen
    # This needs to be outside of any multifactor protected views and therefore cant be in the calorietracker app urls
    path(
        "apple-touch-icon.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("favicon/apple-touch-icon.png")
        ),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG is True:
    urlpatterns += [
        path(
            "admin/", decorator_include(multifactor_protected(factors=0),
                                        admin.site.urls)
        ), ]

else:
    urlpatterns += [
        path(
            "admin/", decorator_include(multifactor_protected(factors=1),
                                        admin.site.urls)
        ), ]

mysite/calorietracker/forms.py
import csv

from bootstrap_datepicker_plus.widgets import DatePickerInput
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django_measurement.forms import MeasurementField
from measurement.measures import Distance, Weight
from cloudinary.forms import CloudinaryFileField

from .models import Log, Setting, Image


class FriendShipRequestForm(forms.Form):
    """docstring for AcceptFriendForm."""

    to_user = forms.ModelChoiceField(get_user_model().objects.all())


class FriendForm(forms.Form):
    """docstring for FriendForm."""

    from_user = forms.ModelChoiceField(get_user_model().objects.all())


class MeasurementWidget(forms.MultiWidget):
    def __init__(
        self,
        float_widget=None,
        unit_choices_widget=None,
        unit_choices=None,
        *args,
        **kwargs
    ):

        self.unit_choices = unit_choices

        if not float_widget:
            float_widget = forms.TextInput(
                attrs={
                    "class": "form-control",
                    "style": "width: 75%; display: inline-block;",
                    "placeholder": "160",
                }
            )

        if not unit_choices_widget:
            unit_choices_widget = forms.Select(
                attrs={
                    "class": "form-control",
                    "style": "width: 25%; display: inline-block;",
                    "placeholder": "160",
                },
                choices=unit_choices,
            )

        widgets = (float_widget, unit_choices_widget)
        super(MeasurementWidget, self).__init__(widgets)

    def decompress(self, value):
        if value:
            choice_units = set([u for u, n in self.unit_choices])

            unit = value.STANDARD_UNIT
            if unit not in choice_units:
                unit = choice_units.pop()

            magnitude = getattr(value, unit)
            return [magnitude, unit]

        return [None, None]


class RegisterForm(UserCreationForm):

    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control form-control-user", "placeholder": "Password"}
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control form-control-user",
                "placeholder": "Repeat Password",
            }
        )
    )

    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
        )

        widgets = {
            "username": forms.TextInput(
                attrs={
                    "class": "form-control form-control-user",
                    "placeholder": "Username",
                }
            ),
            "email": forms.TextInput(
                attrs={
                    "class": "form-control form-control-user",
                    "placeholder": "Email Address  *Optional",
                }
            ),
        }


class LoginForm(AuthenticationForm):

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control form-control-user", "placeholder": "Username"}
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control form-control-user", "placeholder": "Password"}
        )
    )


class ImportCSVForm(forms.Form):

    data_file = forms.FileField(
        label="",
        widget=forms.FileInput(
            attrs={
                "style": "display: inline-block;",
                "accept": ".csv",
            },
        ),
        required=True,
    )

    weight_units = forms.ChoiceField(
        label="What unit is your weight data in?",
        widget=forms.Select(
            attrs={
                "class": "form-control",
                "style": "display: inline-block;",
            },
        ),
        choices=(("lb", "lbs"), ("kg", "kgs")),
        required=True,
    )

    date_format = forms.ChoiceField(
        label="Please specify your date format (Year is optional; will default to the current year)",
        widget=forms.Select(
            attrs={
                "class": "form-control",
                "style": "display: inline-block;",
            },
        ),
        choices=[
            ("MDY", "Month, Day, Year"),
            ("DMY", "Day, Month, Year"),
            ("YMD", "Year, Month, Day"),
            ("YDM", "Year, Day, Month"),
        ],
        required=True,
    )

    csv_overwrite = forms.ChoiceField(
        label="Overwrite existing log entries?",
        widget=forms.Select(
            attrs={
                "class": "form-control",
                "style": "display: inline-block;",
            },
        ),
        choices=[
            ("True", "Yes, overwrite any log entries I have"),
            ("False", "No, don't overwrite my log entries"),
        ],
        required=True,
    )


class ImportMFPForm(forms.Form):
    mfp_start_date = forms.DateField(
        label="Please select your import START date",
        widget=DatePickerInput(
            attrs={
                "style": "display: inline-block;",
            },
        ),
        required=True,
    )
    mfp_end_date = forms.DateField(
        label="Please select your import END date",
        widget=DatePickerInput(
            attrs={
                "style": "display: inline-block;",
            },
        ),
        required=True,
    )
    mfp_data_select = forms.ChoiceField(
        label="Which data would you like to import?",
        widget=forms.Select(
            attrs={
                "class": "form-control",
                "style": "display: inline-block;",
            },
        ),
        choices=[
            ("Weights", "MFP Weight Entries"),
            ("CI", "MFP Caloric Intake Logs"),
        ],
        required=True,
    )
    mfp_overwrite = forms.ChoiceField(
        label="Overwrite existing log entries?",
        widget=forms.Select(
            attrs={
                "class": "form-control",
                "style": "display: inline-block;",
            },
        ),
        choices=[
            ("True", "Yes, overwrite any log entries I have"),
            ("False", "No, don't overwrite my log entries"),
        ],
        required=True,
    )


class LogDataForm(forms.ModelForm):
    class Meta:
        model = Log
        fields = (
            "date",
            "weight",
            "calories_in",
            "calories_out",
            "activity_lvl",
            "front_progress_pic",
            "side_progress_pic",
            "back_progress_pic",
        )

    front_progress_pic = CloudinaryFileField(
        label="Front Facing Progress Pic:",
        widget=forms.FileInput(
            attrs={
                "style": "display: inline-block;",
            }
        ),
        options={
            "folder": "progress_pics",
        },
        required=False,
    )

    side_progress_pic = CloudinaryFileField(
        label="Side Facing Progress Pic:",
        widget=forms.FileInput(
            attrs={
                "style": "display: inline-block;",
            }
        ),
        options={
            "folder": "progress_pics",
        },
        required=False,
    )

    back_progress_pic = CloudinaryFileField(
        label="Back Facing Progress Pic:",
        widget=forms.FileInput(
            attrs={
                "style": "display: inline-block;",
            }
        ),
        options={
            "folder": "progress_pics",
        },
        required=False,
    )

    date = forms.DateField(
        widget=DatePickerInput(
            attrs={
                "style": "display: inline-block;",
            },
        ),
        required=True,
    )

    weight = MeasurementField(
        widget=MeasurementWidget(
            unit_choices=(("lb", "lbs"), ("kg", "kgs")),
        ),
        measurement=Weight,
        required=True,
    )

    calories_in = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={
                "class": "form-control",
                "style": "display: inline-block;",
                "placeholder": "2000",
            }
        ),
        required=True,
    )

    calories_out = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={
                "class": "form-control",
                "style": "display: inline-block;",
            }
        ),
        required=False,
    )

    activity_lvl = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-control",
                "style": "display: inline-block;",
            },
        ),
        choices=Log.choices,
        required=False,
    )


class SettingForm(forms.ModelForm):
    class Meta:
        model = Setting
        fields = [
            "age",
            "sex",
            "height",
            "activity",
            "goal",
            "goal_weight",
            "goal_date",
            "unit_preference",
        ]

    goal_weight = MeasurementField(
        widget=MeasurementWidget(
            unit_choices=(("lb", "lbs"), ("kg", "kgs")),
        ),
        measurement=Weight,
        required=True,
    )

    goal_date = forms.DateField(
        widget=DatePickerInput(
            attrs={
                "style": "display: inline-block;",
            },
        ),
        required=True,
    )

    goal = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-control",
                "style": "display: inline-block;",
            },
        ),
        choices=Setting.goal_choices,
        required=True,
    )

    unit_preference = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-control",

mysite/calorietracker/templates/calorietracker/clients.html
{% extends "extends/base.html" %}
{% load static %}

{% block content %}


<!-- Begin Page Content -->
<div class="container-fluid">

  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Clients</h1>

  </div>

  <!-- Content Row -->
  <div class="row">
    <!-- Logs -->
    <div class="col-xl-12 col-lg-7">
      <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Clients (Click Row to View Analytics)</h6>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-hover"id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Current Weight ({{weights_label}})</th>
                  <th>Goal Weight ({{weights_label}})</th>
                  <th>Goal Date</th>
                  <th>Logging Rate</th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>
<!-- /.container-fluid -->

<!-- Page level global data -->
<script>
var logjson = {{clients_data | safe}}
var units_weight = " ({{weights_label}})"
</script>


<!-- Page level clients datatable -->
<script>
$(document).ready(function() {
  $('#dataTable').DataTable( {
    "data": logjson.data,
    "columns": [
    { "data": "Name" },
    { "data": "Current Weight" },
    { "data": "Goal Weight" },
    { "data": "Goal Date" },
    { "data": "Log Rate" },
    ],
  });
})

$('#dataTable').on('click', 'tbody > tr > td', function (e) {
    // 'this' refers to the current <td>
    e.preventDefault();
    var table = $('#dataTable').DataTable();
    var data = table.row($(this).closest('tr')).data();

    url = "/analytics/" + String(data.uuid) // use user's share token to access full view of analytics.

    location.href=url // redirect
  });
</script>



{% endblock %}

mysite/calorietracker/templates/calorietracker/contacts.html
{% extends "extends/base.html" %}
{% load static %}
{% load friendshiptags %}

{% block content %}

<!-- Begin Page Content -->
<div class="container-fluid">

  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Friends</h1>
  </div>

    <!-- Content Row -->
  <div class="row">

    <!-- Friends Main Card-->
    <div class="col-xl-7 col-lg-7">
      <div class="card w-100 shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header">
          <div class="nav">
            <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
              <li class="nav-item">
                  <a class="nav-link active" id="all-friends-tab" data-toggle="tab" href="#allfriends" role="tab" aria-controls="home" aria-selected="true">All Friends</a>
              </li>

              {% comment %}
              <li class="nav-item">
                  <a class="nav-link" id="followers-friends-tab" data-toggle="tab" href="#followers" role="tab" aria-controls="followers" aria-selected="false">Followers</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" id="following-friends-tab" data-toggle="tab" href="#following" role="tab" aria-controls="following" aria-selected="false">Following</a>
              </li>
              {% endcomment %}

              <li class="nav-item">
                  <a class="nav-link" id="pending-friends-tab" data-toggle="tab" href="#pendingfriends" role="tab" aria-controls="pendingfriends" aria-selected="false">Pending
                    <span id="" class="badge badge-primary badge-counter">{{pending_friends_count|default:"0" }}</span>

                  </a>
              </li>

              <li class="nav-item">
                  <a class="" id="search-friends-tab" data-toggle="tab" href="#searchusers" role="tab" aria-controls="searchusers" aria-selected="false"></a>
              </li>

              <!-- <li class="nav-item">
                  <a class="nav-link" id="blocked-friends-tab" data-toggle="tab" href="#blockedfriends" role="tab" aria-controls="blockedfriends" aria-selected="false">Blocked</a>
              </li>

            </ul>
            <ul class="nav nav-tabs card-header-tabs ml-auto">
              <!-- Nav Item - Search Dropdown (Visible Only XS) -->
              <li class="nav-item dropdown no-arrow d-sm-none">
                <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-search fa-fw"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-left p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                  <form class="form-inline mr-auto w-75 navbar-search">
                    <div class="input-group">
                      <input id="searchbarSm" type="text" oninput="updateLiveSearchSm();" class="form-control bg-light border-0 small" placeholder="Add..." aria-label="Search" aria-describedby="basic-addon2">
                      <div class="input-group-append">
                        <button class="btn btn-primary" type="button" onclick="updateLiveSearchSm();">
                          <i class="fas fa-search fa-sm"></i>
                        </button>
                      </div>
                    </div>
                  </form>
                </div>
              </li>
              <li class="nav-item">
                <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-75 navbar-search">
                  <div class="input-group">
                    <input id="searchbarLg" type="text" oninput="updateLiveSearchLg();" class="form-control bg-light border-0" style="width:150px;" placeholder="Add Friends..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button" onclick="updateLiveSearchLg();">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </li>
            </ul>
          </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          <div class="tab-content" id="myTabContent">

            <div class="tab-pane fade show active" id="allfriends" role="tabpanel" aria-labelledby="all-friends-tab">
              <ul>
                {% for friend in all_friends %}
                  <li class="dropdown-item mb-2 mt-2" style="display: inline-block;" onclick="location.href='{% url 'profile' slug=friend%}';" >
                    <text style='text-decoration: none; font-size: 1.15rem;'>{{friend}}</text>
                    <span class="badge badge-pill badge-success">friend</span>

                    {% if friend in coaches %}
                      <span class="badge badge-pill badge-warning">coach</span>

                      <!-- Remove Coach -->
                      <form class="float-right" action="{% url 'removecoachclient' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" id="id_to_user" name="to_user" value="{{ friend.id }}">
                        <button class="btn btn-danger btn-sm mx-1" type="submit" onclick="return confirm('Are you sure you would like to remove user as a coach?');" name="button">Remove Coach</button>
                      </form>
                    {% else %}
                      {% if friend in clients %}
                        <span class="badge badge-pill badge-info">client</span>
                      {% else %}
                        <!-- Add Coach -->
                        <form class="float-right" action="{% url 'addcoach' %}" method="POST">
                          {% csrf_token %}
                          <input type="hidden" id="id_to_user" name="to_user" value="{{ friend.id }}">
                          <button class="btn btn-warning btn-sm mx-1" type="submit" onclick="return confirm('Are you sure you would like to add user as a coach? Coaches are able to see all your logs and analytics.');" name="button">Add Coach</button>
                        </form>
                      {% endif %}
                    {% endif %}

                    <!-- Remove Friend -->
                    <form class="float-right" action="{% url 'removefriend' %}" method="POST">
                      {% csrf_token %}
                      <input type="hidden" id="id_from_user" name="from_user" value="{{ friend.id }}">
                      <button class="btn btn-danger btn-sm mx-1" type="submit" onclick="return confirm('Are you sure you would like to remove this friend?');" name="button">Remove Friend</button>
                    </form>
                  </li>
                {% endfor %}
              </ul>
            </div>

            {% comment %}
            <div class="tab-pane fade" id="followers" role="tabpanel" aria-labelledby="followers-friends-tab">...</div>
            <div class="tab-pane fade" id="following" role="tabpanel" aria-labelledby="following-friends-tab">...</div>
            {% endcomment %}

            <div class="tab-pane fade" id="pendingfriends" role="tabpanel" aria-labelledby="pending-friends-tab">
              <ul>
                {% for friend_request in unrejected_friend_requests %}
                  <li class="dropdown-item mb-2 mt-2 font-weight-bold" style="display: inline-block;" onclick="location.href='{% url 'profile' slug=friend_request.from_user%}';">
                      <text style='text-decoration: none; font-size: 1.15rem;'>{{ friend_request.from_user }}</text>

                    <!-- Accept Friend -->
                    <form class="float-right" action="{% url 'acceptfriend' %}" method="POST">
                      {% csrf_token %}
                      <input type="hidden" id="id_from_user" name="from_user" value="{{ friend_request.from_user.id }}">
                      <button class="btn btn-sm btn-success ml-2" type="submit" name="button">Accept</button>
                    </form>

                    <!-- Reject Friend -->
                    <form class="float-right" action="{% url 'rejectfriend' %}" method="POST">
                      {% csrf_token %}
                      <input type="hidden" id="id_from_user" name="from_user" value="{{ friend_request.from_user.id }}">
                      <button class="btn btn-sm btn-danger" type="submit" name="button">Reject</button>
                    </form>
                  </li>

                {% endfor %}

                {% for friend_request in pending_outgoing_requests %}
                  <li class="dropdown-item mb-2 mt-2 font-weight-bold" style="display: inline-block;" onclick="location.href='{% url 'profile' slug=friend_request.to_user%}';">
                      <text style='text-decoration: none; font-size: 1.15rem;'>{{ friend_request.to_user }}</text>

                    <!-- Cancel Friend Request -->
                    <form class="float-right" action="{% url 'cancelfriendrequest' %}" method="POST">
                      {% csrf_token %}
                      <input type="hidden" id="id_to_user" name="to_user" value="{{ friend_request.to_user.id }}">
                      <button class="btn btn-sm btn-info" type="submit" name="button">Cancel Request</button>
                    </form>
                  </li>

                {% endfor %}
              </ul>
            </div>

            <div class="tab-pane fade" id="blockedfriends" role="tabpanel" aria-labelledby="blocked-friends-tab">
            </div>

            <div class="tab-pane fade" id="searchusers" role="tabpanel" area-labelledby="search-users-tab">
              <div id="ErrorText">Search for a user</div>
              <!-- User Livesearch List Results -->
              <ul id='search-results'>
                <li class="dropdown-item d-flex align-items-center" style="display: inline-block;" href="#"></li>
              </ul>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<script>
// Global variables for user_search.js are defined here as they require django tags

// store current friends list for filtering search results
var all_friends = [] 
{% for friend in all_friends %}
  all_friends.push('{{ friend }}')
{% endfor %}

// todo improve html elements building so its more readable and not purely string based.

// button next to each search result 
let button = '<button class="btn btn-sm btn-success" type="submit" name="button">Add Friend</button>'

// form action for each search result
let friend_request_action = 'action="{% url 'sendfriendrequest' %}'

// form csrf 
let csrf = '{% csrf_token %}'

// current user username for filtering search results
let username = '{{ user.get_username }}'

// pending friendship requests for the user for filtering search results
let pending_outgoing_requests_usernames = []
{% for friend_request in pending_outgoing_requests %}
  pending_outgoing_requests_usernames.push('{{ friend_request.to_user }}')
{% endfor %}

// console.log(all_friends)
// console.log(pending_outgoing_requests_usernames)
</script>
<script src="{% static "js/user_search.js" %}">// Live Search Users for Adding Friends</script>

{% endblock %}

mysite/calorietracker/templates/calorietracker/date.html
{% load crispy_forms_field %}

<div id="div_{{ field.auto_id }}" class="control-group{% if form_show_errors and field.errors %} error{% endif %} {% if field.field.widget.attrs.class %} {{ field.field.widget.attrs.class }}{% endif %}">

    {% if field.label %}
        <label for="{{ field.id_for_label }}" class="control-label {% if field.field.required %}requiredField{% endif %}">
            {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
        </label>
    {% endif %}

    <div class="controls">
        <div class="input-append">
            {% crispy_field field %}
            <span class="add-on {% if active %}active{% endif %}">{{ crispy_appended_text|safe }}</span>
        </div>

        {% include 'bootstrap/layout/help_text_and_errors.html' %}
    </div>
</div>

mysite/calorietracker/templates/calorietracker/subscription.html
{% extends "extends/base.html" %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<!-- Begin Page Content -->
<div class="container-fluid">

  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Subs</h1>
  </div>


</div>
<!-- /.container-fluid -->

{% endblock %}